### ISSUE TITLE
Could you please help me to solve the issue

### ISSUE THREAD

**Issue by mohanvrk** [Ethan-Chen-plus/fine_tune_dp#1]
Hello @Ethan-Chen-plus 

I was trying to run the code given in your jupyternotebook, but the following error is bothering. I request you please help me.

Thanks and regards
Veera

[INFO|trainer.py:752] 2023-09-21 10:45:12,943 >> The following columns in the training set don't have a corresponding argument in `GradSampleModule.forward` and have been ignored: input_ids, attention_mask. If input_ids, attention_mask are not expected by `GradSampleModule.forward`,  you can safely ignore this message.
[INFO|trainer.py:1712] 2023-09-21 10:45:12,953 >> ***** Running training *****
[INFO|trainer.py:1713] 2023-09-21 10:45:12,955 >>   Num examples = 0
[INFO|trainer.py:1714] 2023-09-21 10:45:12,956 >>   Num Epochs = 3
[INFO|trainer.py:1715] 2023-09-21 10:45:12,958 >>   Instantaneous batch size per device = 32
[INFO|trainer.py:1717] 2023-09-21 10:45:12,960 >>   Training with DataParallel so batch size has been adjusted to: 64
[INFO|trainer.py:1718] 2023-09-21 10:45:12,961 >>   Total train batch size (w. parallel, distributed & accumulation) = 128
[INFO|trainer.py:1719] 2023-09-21 10:45:12,963 >>   Gradient Accumulation steps = 2
[INFO|trainer.py:1720] 2023-09-21 10:45:12,965 >>   Total optimization steps = 22,968
[INFO|trainer.py:1721] 2023-09-21 10:45:12,967 >>   Number of trainable parameters = 147,456
[INFO|integration_utils.py:716] 2023-09-21 10:45:12,973 >> Automatic Weights & Biases logging enabled, to disable set os.environ["WANDB_DISABLED"] = "true"
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[119], line 2
      1 try:
----> 2     trainer.train()
      3 finally:
      4     eps_prv = trainer.get_prv_epsilon()

File /opt/conda/lib/python3.10/site-packages/transformers/trainer.py:1553, in Trainer.train(self, resume_from_checkpoint, trial, ignore_keys_for_eval, **kwargs)
   1551         hf_hub_utils.enable_progress_bars()
   1552 else:
-> 1553     return inner_training_loop(
   1554         args=args,
   1555         resume_from_checkpoint=resume_from_checkpoint,
   1556         trial=trial,
   1557         ignore_keys_for_eval=ignore_keys_for_eval,
   1558     )

File /opt/conda/lib/python3.10/site-packages/transformers/trainer.py:1813, in Trainer._inner_training_loop(self, batch_size, args, resume_from_checkpoint, trial, ignore_keys_for_eval)
   1810     rng_to_sync = True
   1812 step = -1
-> 1813 for step, inputs in enumerate(epoch_iterator):
   1814     total_batched_samples += 1
   1815     if rng_to_sync:

File /opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:681, in _BaseDataLoaderIter.__next__(self)
    678 if self._sampler_iter is None:
    679     # TODO([https://github.com/pytorch/pytorch/issues/76750)](https://github.com/pytorch/pytorch/issues/76750)%3C/span%3E)
    680     self._reset()  # type: ignore[call-arg]
--> 681 data = self._next_data()
    682 self._num_yielded += 1
    683 if self._dataset_kind == _DatasetKind.Iterable and \
    684         self._IterableDataset_len_called is not None and \
    685         self._num_yielded > self._IterableDataset_len_called:

File /opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:1376, in _MultiProcessingDataLoaderIter._next_data(self)
   1374 else:
   1375     del self._task_info[idx]
-> 1376     return self._process_data(data)

File /opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:1402, in _MultiProcessingDataLoaderIter._process_data(self, data)
   1400 self._try_put_index()
   1401 if isinstance(data, ExceptionWrapper):
-> 1402     data.reraise()
   1403 return data

File /opt/conda/lib/python3.10/site-packages/torch/_utils.py:461, in ExceptionWrapper.reraise(self)
    457 except TypeError:
    458     # If the exception takes multiple arguments, don't try to
    459     # instantiate since we don't know how to
    460     raise RuntimeError(msg) from None
--> 461 raise exception

IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 1764, in __getitem__
    return self._getitem(
  File "/opt/conda/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 1748, in _getitem
    pa_subtable = query_table(self._data, key, indices=self._indices if self._indices is not None else None)
  File "/opt/conda/lib/python3.10/site-packages/datasets/formatting/formatting.py", line 486, in query_table
    _check_valid_index_key(key, size)
  File "/opt/conda/lib/python3.10/site-packages/datasets/formatting/formatting.py", line 429, in _check_valid_index_key
    raise IndexError(f"Invalid key: {key} is out of bounds for size {size}")
IndexError: Invalid key: 31088 is out of bounds for size 0

**Comment by Ethan-Chen-plus** [comment]
Hi @mohanvrk 
Thanks for your question!
I think you need the flag --remove_unused_columns False
It's the same as https://github.com/microsoft/dp-transformers/issues/34
I will submit a PR to address this issue. Thank you for pointing it!
